@extends('layouts.app')
@section('content')
<div class="page-heading"><div><span class="eyebrow">Ruang kerja operator</span><h2>Input Data Pertanahan</h2><p>Simpan data sebagai draft, lalu ajukan untuk ditinjau.</p></div><span class="role-badge">{{ auth()->user()->roles()->where('is_active',true)->value('name') }}</span></div>
<div class="stepper"><div><b>1</b><span>Pilih indikator</span></div><div><b>2</b><span>Isi nilai</span></div><div><b>3</b><span>Simpan dan ajukan</span></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-error">{{ $errors->first() }}</div>@endif
<div class="panel entry-panel"><form method="post" action="{{ route('data-entry.store') }}" class="entry-form" data-submit-state>@csrf
<label>Indikator<select name="indicator_code" required><option value="">Pilih indikator</option>@foreach($indicators as $indicator)<option value="{{ $indicator->canonical_code }}" data-unit="{{ $indicator->unit ?? 'Tanpa satuan' }}">{{ $indicator->name }}</option>@endforeach</select></label>
<label>Wilayah<select name="region_id" required>@foreach($regions as $region)<option value="{{ $region->id }}">{{ $region->name }}</option>@endforeach</select></label><label>Periode<select name="as_of_date" required>@foreach($snapshots as $snapshot)<option value="{{ $snapshot->as_of_date->format('Y-m-d') }}">{{ $snapshot->as_of_date->format('d F Y') }}</option>@endforeach</select></label><label>Nilai<input name="value" required inputmode="decimal"></label><label>Catatan (opsional)<textarea name="note" rows="3"></textarea></label><div class="selection-summary">Satuan ditentukan oleh definisi indikator dan sumber ditentukan server.</div><button type="submit" class="primary-button">Simpan Draft</button></form></div>
<div class="panel"><div class="panel-heading"><h3>Draft saya</h3><span class="status-dot">{{ $drafts->count() }} draft</span></div>@if($drafts->isEmpty())<div class="empty-state">Belum ada draft. Isi formulir di atas untuk memulai.</div>@else<div class="table-wrap"><table><thead><tr><th>Indikator</th><th>Wilayah</th><th>Periode</th><th>Revisi</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@foreach($drafts as $draft)<tr><td>{{ $draft->observation->indicator->name }}</td><td>{{ $draft->observation->region->name }}</td><td>{{ $draft->observation->snapshot->as_of_date->format('d F Y') }}</td><td>{{ $draft->revision_number }}</td><td><span class="status-badge draft">Draft</span></td><td><form method="post" action="{{ route('data-entry.submit',$draft) }}" data-submit-state>@csrf<button type="submit" class="secondary-button">Ajukan</button></form></td></tr>@endforeach</tbody></table></div>@endif</div>
@endsection
