<?php
namespace Tests\Feature;
use Tests\TestCase; use App\Models\{User,Role,Region,Indicator,ObservationRevision}; use App\Services\ManualObservationService; use Illuminate\Foundation\Testing\DatabaseTransactions; use Illuminate\Support\Facades\{DB,Hash}; use Illuminate\Support\Str;
class WebReviewTest extends TestCase
{
 use DatabaseTransactions; private Region $region;
 protected function setUp(): void { parent::setUp(); $this->assertSame('dashboard_pertanahan_test',DB::connection()->getDatabaseName()); $this->region=Region::where('level','regency_city')->firstOrFail(); }
 private function user(string $role): User { $u=User::create(['name'=>'Review test','email'=>Str::uuid().'@test.local','password'=>Hash::make('secret'),'is_active'=>true]); $u->roles()->attach(Role::where('code',$role)->firstOrFail()); $u->regionScopes()->attach($this->region); return $u; }
 private function submitted(User $u, string $code='V.2'): ObservationRevision { $i=Indicator::where('canonical_code',$code)->firstOrFail(); $r=app(ManualObservationService::class)->create($u,$i,$this->region,['as_of_date'=>'2026-09-06','value'=>12]); return app(ManualObservationService::class)->transition($u,$r,'submitted',1,null); }
 public function test_guest_and_non_admin_are_denied(): void { $this->get('/review')->assertRedirect('/login'); $this->actingAs($this->user('operator_pemda'))->get('/review')->assertForbidden(); }
 public function test_super_admin_can_review_and_publish_submitted_revision(): void { $operator=$this->user('operator_pemda'); $revision=$this->submitted($operator); $admin=$this->user('super_admin'); $page=$this->actingAs($admin)->get('/review')->assertOk()->assertSee('Review Data')->assertSee('Total PBB')->assertSee('name="_token"',false); $this->assertStringContainsString('method="post"',$page->getContent()); $this->post(route('review.publish',$revision))->assertRedirect()->assertSessionHas('success'); $this->assertSame('published',$revision->fresh()->status); $this->assertDatabaseHas('published_values',['observation_revision_id'=>$revision->id,'published_by'=>$admin->id]); }
 public function test_super_admin_can_reject_and_invalid_transition_is_blocked(): void { $operator=$this->user('operator_kantah'); $revision=$this->submitted($operator); $admin=$this->user('super_admin'); $this->actingAs($admin)->from('/review')->post(route('review.reject',$revision),['reason'=>'Perbaiki'])->assertRedirect()->assertSessionHas('success'); $this->assertSame('rejected',$revision->fresh()->status); $this->post(route('review.publish',$revision))->assertStatus(409); }
 public function test_review_actions_require_csrf(): void { $this->actingAs($this->user('super_admin'))->post('/review/revisions/999/publish')->assertStatus(404); }
 public function test_only_submitted_revisions_are_in_queue_and_audit_events_are_safe(): void { $operator=$this->user('operator_pemda'); $submitted=$this->submitted($operator); $admin=$this->user('super_admin'); $this->actingAs($admin)->post(route('review.reject',$submitted),['reason'=>'Perbaiki'])->assertRedirect(); $this->assertSame('rejected',$submitted->fresh()->status); $this->assertSame(0,ObservationRevision::where('status','submitted')->count()); $this->actingAs($admin)->get('/review')->assertOk()->assertSee('Tidak ada data menunggu review', false); $this->assertSame(3,DB::table('revision_status_events')->where('observation_revision_id',$submitted->id)->count()); $this->assertStringNotContainsString('secret',DB::table('audit_events')->where('entity_id',$submitted->id)->value('metadata')??''); }
}
