<?php
namespace App\Http\Controllers;
use App\Models\Indicator; use App\Models\ObservationRevision; use App\Models\Region; use App\Models\ReportingSnapshot; use App\Services\ManualObservationService; use Illuminate\Http\Request; use Illuminate\Support\Facades\Gate;
class WebManualEntryController extends Controller
{
 public function __construct(private ManualObservationService $service) {}
 private function allowed(): bool { $u=auth()->user(); return $u->hasActiveRole('operator_pemda')||$u->hasActiveRole('operator_kantah'); }
 public function index(){ abort_unless($this->allowed(),403); $u=auth()->user(); $categories=\App\Models\Category::with('submenus')->where('is_active',1)->orderBy('display_order')->get(); $selectedSubmenu=$selectedRegion=$selectedDate=null; $regions=Region::where('is_active',1)->whereHas('users',fn($q)=>$q->whereKey($u->id))->orderBy('name')->get(); $indicators=Indicator::with('owner')->where('is_active',1)->where('allows_manual_input',1)->whereHas('owner',fn($q)=>$q->whereIn('code',['pemda','kantah']))->orderBy('display_order')->get()->filter(fn($i)=>$u->hasActiveRole('operator_'.$i->owner->code)); $snapshots=ReportingSnapshot::orderByDesc('as_of_date')->get(); $drafts=ObservationRevision::with(['observation.indicator','observation.region','observation.snapshot'])->where('created_by',$u->id)->where('status','draft')->latest()->get(); return view('data-entry',compact('categories','selectedSubmenu','selectedRegion','selectedDate','regions','indicators','snapshots','drafts')); }
 public function store(Request $r){ abort_unless($this->allowed(),403); $d=$r->validate(['indicator_code'=>'required|string','region_id'=>'required|integer','as_of_date'=>'required|date_format:Y-m-d','value'=>'required','note'=>'nullable|string|max:1000']); $i=Indicator::where('canonical_code',$d['indicator_code'])->where('is_active',1)->firstOrFail(); $region=Region::whereKey($d['region_id'])->where('is_active',1)->firstOrFail(); Gate::forUser($r->user())->authorize('update',[$i,$region]); $this->service->create($r->user(),$i,$region,$d); return back()->with('success','Draft berhasil disimpan.'); }
 public function submit(Request $r, ObservationRevision $revision){ abort_unless($this->allowed(),403); $revision->loadMissing('observation.indicator.owner','observation.region'); Gate::forUser($r->user())->authorize('update',[$revision->observation->indicator,$revision->observation->region]); $this->service->transition($r->user(),$revision,'submitted',(int)$revision->revision_number,$r->input('reason')); return back()->with('success','Draft dikirim untuk ditinjau.'); }
}
